README.md

The original link pointed to the etcd issue tracker not this one

Fix "low hanging fruits" link

---

block/blockfile.go

block: always release locks on errors

---

Documentation/getting-started.md

Documentation: fix typo in git URL

---

block/aoe/aoe.go

Trying to make this more testable.  This is the standard method name that is also used in `x/net/ipv{4,6}`, and I've implemented it in package `raw` as well:
https://godoc.org/golang.org/x/net/ipv4#PacketConn.SetBPF
https://godoc.org/golang.org/x/net/ipv6#PacketConn.SetBPF
https://godoc.org/github.com/mdlayher/raw#Conn.SetBPF
Having some more `glide` woes: https://gist.github.com/mdlayher/3afb1b93ef42faeffb0e09408aabb60f, but `github.com/mdlayher/raw` will need another bump.

block/aoe: conditionally attach BPF filter if SetBPF method present

---

block/aoe/aoe.go

Also noticed an unchecked `f.Sync()` error and added a check.

block/aoe: cancel and wait for background goroutines to stop on Close

---

Documentation/getting-started.md

This adds a small section on how to get started using rkt.

Documentation: getting started using rkt

---

block/aoe/aoe.go
block/aoe/aoe_test.go

This is a big one.  I tried to set up some kind of sane testing framework for the AoE server.  After some trial and error, this is what I came up with.
This test, and others, will essentially verify that for a given AoE request, an expected AoE response is provided.
It's definitely not the prettiest piece of code I've ever written, and I'd be happy to hear any feedback you all may have about making it nicer.

block/aoe: initial server tests

---

glide.lock

Fixed a bug in my AoE package: https://github.com/mdlayher/aoe/commit/63bdfd7f5c50809059b7b6de1cf37c2e330c5f81.
Need to update this to add more tests.

glide.lock: bump github.com/mdlayher/aoe

---

README.md

rel. https://github.com/coreos/coreos-baremetal/pull/229

README: Add link to Torus with coreos-baremetal

---

cmd/torusblk/aoe.go

Mark AoE as experimental as the rest of torus. Fixes #168

---

block/aoe/aoe_test.go

Left a `TODO` to deeply inspect the returned data, but this should cover it for now.

block/aoe: test ATA identify request

---

Documentation/admin-guide.md
Procfile
cmd/torusblk/main.go
cmd/torusctl/common.go
cmd/torusctl/init.go
cmd/torusctl/ring.go
cmd/torusctl/torusctl.go
cmd/torusctl/wipe.go
cmd/torusd/main.go
config.go
internal/flagconfig/flagconfig.go
metadata/etcd/etcd.go
metadata/etcd/global_funcs.go

From #292, but with the merge conflict fixed :)

Add etcd TLS client certificate authentication

---

cmd/torusctl/block_dump_load.go

Fix dump progress

---

cmd/torusd/main.go

Fixes https://github.com/coreos/torus/issues/319

torusd: Remove unused value from torusd

---

cliconfig/config.go
cmd/torusctl/config.go
cmd/torusctl/torusctl.go
internal/flagconfig/flagconfig.go

fixes https://github.com/coreos/torus/issues/176

Support cli config .torus/config.json

---

cmd/torusctl/ring.go

fixes https://github.com/coreos/torus/issues/364

ring: allow ring manual-change when there are no peers in ring

---

cmd/torusblk/aoe.go
cmd/torusblk/nbd.go
cmd/torusblk/tcmu.go
cmd/torusctl/block_dump_load.go
cmd/torusctl/block_snapshot.go
errors.go

fixes https://github.com/coreos/torus/issues/333

Return command functions to close defer

---

storage/mmap_file.go

Fixes https://github.com/coreos/torus/issues/342

mfile: support expanding node storage size

---

cmd/torusctl/init.go

fixes https://github.com/coreos/torus/issues/351

init: Support view option to check some metadata in the cluster

---

internal/nbd/nbd.go

fixes https://github.com/coreos/torus/issues/295

nbd: handle NBD_SET_FLAGS error due to old kernel version

---

cmd/torusctl/common.go
cmd/torusctl/list-peers.go
cmd/torusctl/volume.go

fixes https://github.com/coreos/torus/issues/376

torusctl: support SI size output

---

block/temp.go
cmd/torusctl/volume.go
metadata.go
metadata/etcd/etcd.go
metadata/temp/temp.go

fixes https://github.com/coreos/torus/issues/339

torusctl: support volume list to show volume status

---

glide.lock

fixes https://github.com/coreos/torus/issues/384

aoe: update to aoe fixed statusready issue

---

cmd/torusblk/aoe.go

fixes https://github.com/coreos/torus/issues/381

aoe: close servers by defer

---

ring/mod.go

fixes https://github.com/coreos/torus/issues/427

mod: fixed gopanic when enough nodes doesn't exist

---

README.md

"is a platform that is a perfect platform" -> "is a perfect platform"

wording in the readme
