block/aoe/aoe.go
This way, two AoE devices can happily coexist on the same machine without trampling on each other's traffic.
A novel improvement of this idea would be to look into making a BPF filter using `x/net/bpf` to filter the traffic from the raw socket before it ever reaches the Go program.
=> block/aoe: ignore requests meant for other servers

block/aoe/aoe.go
I added functionality tonight to my raw sockets package to enable attaching a BPF program to the raw socket.  `glide` gave me some difficulties so that package bump is not included here.  I'd be happy to look into getting that done tomorrow.
This is the improvement I mentioned in #184 , and should stop the AoE server from getting bogged down handling requests that it doesn't care about.
=> block/aoe: use BPF to filter requests for other servers

.gitignore, .travis.yml, Documentation/getting-started.md, Makefile, Procfile
When building from source, don't recommend using "go get". Instead
clone and populate the vendor directory using glide.
This updates the perceived issue with #189
The "go get" was removed because it downloads a lot of packages but
not enough to actually build torus. See comment [here](
https://github.com/coreos/torus/pull/190#issuecomment-223345034).
Since this introduces another binary, I've moved the default build to
use a "bin" directory.
cc @barakmich
=> *: Use glide in Makefile

README.md
Minor update to show travis-ci project build status as well as godoc link.
=> Add build status and godoc links

contrib/kubernetes/postgres-oneshot.yaml
The existing selector doesn't match the postgres-torus pod. If you run 
```
kubectl get endpoints
NAME                  ENDPOINTS          AGE
postgres-torus        <none>             48m
```
The pod should be available in the ENDPOINTS
After changing  the label on the deployment pod you can see the pod
```
kubectl get endpoints
NAME                  ENDPOINTS          AGE
postgres-torus        172.23.59.7:5432   49m
```
:shipit:
=> fixed endpoint selector for postgres service

contrib/kubernetes/README.md
The initial psql database seed needs stdin to read from the file redirect `< test-data.sql`
This simply adds `-i` to the exec command to send stdin to the pod.
Thanks @barakmich for the help figuring it out.
=> Fixed the psql db seed

cmd/torusctl/torusctl.go, cmd/torusctl/wipe.go
still need to call RegisterMetadataWipe somewhere.
=> cmd/torusctl: register wipe and strip prompt whitespace

contrib/kubernetes/postgres-oneshot.yaml
After reading through the rest of the README example instead of changing all of the README searches I switched the service selector, deployment, and pod labels to app=postgres-torus.
The rest of the README works for me now.
=> Using app= selector instead of name

block/aoe/device.go
Easy one.  Might as well use the built-in interface instead of duplicating it on our own.
=> block/aoe: use io.Closer in Device interface

distributor/protocols/tdp/tdp.go, distributor/protocols/tdp/tdp_test.go
This PR fixes a race in the tdp server close and TestPutBlock test.
Fixes #201
=> Race fixes in tdp server and tests

metadata/etcd/etcd.go
Not sure if the wipe function registration was intentionally removed or it was just missing.
The wipeEtcdMetadata function was already implemented but not registered
causing a panic calling `torusctl wipe`.
This patch registers the wipe function.
=> metadata/etcd: register wipe function

block/aoe/aoe_test.go, glide.lock, glide.yaml
Adds my `bpftest` package to enable testing the BPF program in `block/aoe`, and adds some tests that prove it is working correctly.
=> Add AoE BPF filter tests

distributor/storage.go
When writing a block fails an all peers a nil error is returned (since
err is nil in that scope).
This cause the volume to fail opening again since BlockFile.Sync
thinks that f.File.SyncINode() wrote the inode block to at least one
store and so it'll write the inode metadata. On next volume opening the
inode block cannot be retrieved leaving the volume inaccessible.
This patch fixes distributor/storage.WriteBlock to return an error if
writing the block fails on all the peers.
Should fix #250
=> distributor/storage: fix wrong nil error when writing fails on all peers

errors.go, heartbeat.go, metadata.go, metadata/etcd/etcd.go, metadata/temp/temp.go, server.go
If a server cannot communicate with etcd for a time greater then the lease
timeout (30s) its lease will expire and the server won't reregister
requiring it to be restarted.
This patch fixes this making the server, inside the heartbeat goroutine,
renew the current lease or create a new lease if expired and use this
one to register itself.
This should fix #252 and can be a starting point for option 2 in https://github.com/coreos/torus/issues/230#issuecomment-224092476.
=> server: create new lease if expired

cmd/torusctl/peer.go
Fix error message for ``"torusctl peer remove"`` to ``"couldn't remove peer from ring"``, as it's a remove action.
Also improve help messages a little for ``"torusctl peer add"`` and ``"remove"``, to indicate that they need a parameter either ADDRESS or UUID.
=> cmd/torusctl: fix error & help messages for torusctl peer

distributor/client.go
This patch makes the distClient mutex locking/unlocking more fine
grained to avoid having the distClient mutex locked when calling
server.[Get|Update]PeerMap
This should fix this deadlock:
during some HA tests, stopping/starting various torusd processes, noticed that the other `torusd` and `torusblk` were all blocked. I got a stacktrace of all the processes and I found this possible deadlock (in both the `torusd` and `torusblk` processes).
```
goroutine 87 [semacquire, 53 minutes]:
sync.runtime_Semacquire(0xc820150234)
/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc820150230)
/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/coreos/torus.(*Server).GetPeerMap(0xc820150200, 0x0)
/home/sgotti/golang/src/github.com/coreos/torus/server.go:98 +0x4c …
```
=> distclient: fix deadlock between server and distclient

Makefile, cmd/torusd/main.go, distributor/protocols/protocols.go
1. Added more checks of parsed peer-addr URL to prevent panic
2. Fixed error processing
=> #242 cmd/torusd: extend peer address parsing to avoid panic

ring/ketama.go, ring/ketama_test.go, ring/ring_main.go
The Ketama hash may not assign points to servers that are particularly
small compared to the total storage. This makes some sense -- they can't
cover much. However, this causes errors, and we need to return a full
permutation, so simply append the small ones as "overflow". Fixes #246.
Rings can also declare their replication factor as being higher than the
number of nodes they contain. This causes panics. Raise a warning when
such a ring is detected, but continue operation. Fixes #219.
=> ring: Append Ketama nodes, not panic on small rings

Makefile, heartbeat.go, metadata/temp/temp.go, storage/mfile.go
This PR turns on the race detector for all go tests and fixes some
code that currently triggers race errors.
closes #201
=> *: turn on race detector for testing

block/aoe/aoe_test.go
=> block/aoe: add test that indicates MAC mask list is unimplemented

block/aoe/interface_test.go
=> block/aoe: find loopback interface for TestInterfaceClose

block/aoe/aoe_test.go, glide.lock, glide.yaml
Got my changes merged into `x/net/bpf`!
=> block/aoe: use new x/net/bpf.VM type in tests

Documentation/getting-started.md, Documentation/snapshotting.md, cmd/torusctl/block_snapshot.go, cmd/torusctl/list-peers.go, cmd/torusctl/table.go, cmd/torusctl/volume.go, glide.lock, glide.yaml
Now more consistent:
```
ADDRESS                 UUID                                  SIZE     USED  MEMBER  UPDATED       REB/REP DATA
http://127.0.0.1:40000  b2a2cbe6-38b7-11e6-ab37-5ce0c5527cf4  5.0 GiB  0 B   OK      1 second ago  0 B/sec
http://127.0.0.1:40002  b2a2cbf8-38b7-11e6-9404-5ce0c5527cf4  5.0 GiB  0 B   OK      1 second ago  0 B/sec
http://127.0.0.1:40001  b2a2cc9e-38b7-11e6-b607-5ce0c5527cf4  5.0 GiB  0 B   OK      1 second ago  0 B/sec
```
/cc @robszumski
=> Fix CLI Tables. Fixes #283

.gitignore, Makefile
A few small changes to allow for cross compiling.
Typical usage would be ```make V=1 BUILD_ENV_FLAGS="GOARCH=arm64"```
=> Add cross compile support

cmd/torusblk/tcmu.go, glide.lock, glide.yaml, internal/tcmu/commands.go, internal/tcmu/connect.go
This adds `torusblk tcmu [VOLNAME]` which uses the TCM in Userspace module (and the sister library, https://github.com/coreos/go-tcmu) to talk to the Linux kernel SCSI stack.
This requires a recent-ish kernel -- 4.2 or greater, and 4.6 for better performance -- but is far more stable and generally faster than the equivalent NBD connection.
Followup, add documentation surrounding this.
=> *: Add TCMU support to Torus

cmd/torusblk/main.go
This patch changed to:
* add debug option to torusblk
* set capnslog.INFO to the torusblk's default loglevel (same as torusd)
=> torusblk: add debug option to torusblk

cmd/torusblk/completion.go, cmd/torusblk/main.go, cmd/torusctl/completion.go, cmd/torusctl/torusctl.go, cmd/torusd/main.go
* This patch includes `completion` sub-command for `torusctl` and `torusblk` and `completion`option for `torusd` to generate bash completion shells.
=> Support generating bash completion shells

file.go
Remove `ErrAgain` from `openWrite()`, since ErrAgain is not returned and `CommitINodeIndex()` retry through `AtomicModifyKey()`.
=> file: tiny: remove ErrAgain and retry

blockset/replication.go
fixes https://github.com/coreos/torus/issues/370
This patch contains changes:
- to use `defaultReplication` with `2`.
- replication's `Trim()` skips `ZeroBlock()` initialization first time to avoid out of range error.
=> blockset: use default number of replication as two

distributor/rebalance/tick.go
- This patch stops using variable `outerr` and return `nil` or `io.EOF` explicitly, since `outerr` is never assigned "error".
=> rebalance: Tick returns nil explicitly

block/volume.go, cmd/torusblk/nbd.go, cmd/torusctl/list-peers.go, distributor/client.go, distributor/distributor.go, distributor/distributor_test.go, file.go, file_blackbox_test.go, integration/integration_test.go, local_server.go, metadata.go, metadata/etcd/etcd.go, metadata/temp/temp.go
All implementations of MetadataService.GlobalMetadata() never fail.
=> GobalMetadata doesn't return error

storage/mfile.go
Current log output missed space. This patch added the space between debug/error messages and brockref.
=> mfile: tiny: fix to output BlockRef

internal/nbd/nbd.go
Domain and type were swapped. By accident they both have value 0x1 so the call still worked. See http://man7.org/linux/man-pages/man2/socket.2.html
=> nbd: fix Socketpair call

block/aoe/aoe.go, block/aoe/aoe_test.go
- This patch removes DefaultServerOptions struct which is used by only one test case.
=> aoe: remove default options to specify major and minor numbers

block/aoe/aoe.go, block/aoe/frame.go
Currently, `torusblk aoe vol_name lo 1 1`  with `--debug` keep outputting the data, address and header and they are too much. This patch enables to output Header arguments, but they are moved to `Trace` level.
=> aoe: output header arg with trace level

Documentation/getting-started.md, block/aoe/aoe.go, cmd/torusblk/nbd.go, internal/nbd/nbd.go, internal/tcmu/connect.go
fixes https://github.com/coreos/torus/issues/355
=> torusblk: output common message when attached volume to device and started loop

distributor/client.go
distributor: return ErrNoPeer when get connection failed
Since getConn() tries to get connection, the error should be no peers
rather than block unavailable. On top of that, as all of other getConn()
return ErrNoPeer, it should have consistent policy.
=> distributor: return ErrNoPeer instead of ErrBlockUnavailable when get connection failed

distributor/storage.go
distributor: output error and retry count in readWithBackoff
Currently readWithBackoff() retry to get blocks without warning
messages. This patch changes to output warning message when get blocks
failed from remote peers.
=> distributor: tiny: output error and retry count in readWithBackoff

distributor/protocols/tdp/client.go, distributor/protocols/tdp/tdp.go
This patch changes the error messages in tdp to use clog rather than fmt.Println.
=> tdp: tiny: improve error messages in tdp
